### ISSUE TITLE
TypeError: wikibase-sense claim parser isn't implemented

### ISSUE THREAD

**Issue by YovaKem** [maxlath/wikibase-sdk#68]
I encountered this error:

```
TypeError: wikibase-sense claim parser isn't implemented
        Claim id: undefined
        Please report to https://github.com/maxlath/wikidata-sdk/issues
    at parse (~/node_modules/wikidata-sdk/lib/helpers/parse_claim.js:93:31)
    at simplifyClaim (~/node_modules/wikidata-sdk/lib/helpers/simplify_claims.js:96:13)
    at ~/node_modules/wikidata-sdk/lib/helpers/simplify_claims.js:33:19
    at Array.map (<anonymous>)
    at simplifyPropertyClaims (~/node_modules/wikidata-sdk/lib/helpers/simplify_claims.js:33:6)
    at simplifyClaims (~/node_modules/wikidata-sdk/lib/helpers/simplify_claims.js:14:24)
    at simplifyClaim (~/node_modules/wikidata-sdk/lib/helpers/simplify_claims.js:142:28)
    at ~/node_modules/wikidata-sdk/lib/helpers/simplify_claims.js:33:19
    at Array.map (<anonymous>)
    at simplifyPropertyClaims (~/node_modules/wikidata-sdk/lib/helpers/simplify_claims.js:33:6)
```

command I use:

`curl https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.json.gz | gzip -d | ~/node_modules/.bin/wikidata-filter -s '{"keepRichValues":"true","keepQualifiers":"true"}' --claim org_claim > organizations.ndjson`

where org_claim is a rather long list of ids, but it starts like this:

`P31:Q43229,Q7275,Q11032,Q38723,Q41298,Q62447`

**Comment by YovaKem** [comment]
I wouldn't mind if this wikibase-sense claim just got ignored and the process continued, but currently it breaks. The last line I forgot to paste above is

`curl: (23) Failed writing body (342 != 16384)`

**Comment by maxlath** [comment]
I added support for lexemes, forms, and senses in `wikidata-sdk@v7.4.0` and updated it in `wikidata-filter@v4.0.5`, that should not crash now
